name: OpenTofu Deploy to AWS

on:
    push:
        branches:
            - main  # Triggers deployment when code is merged into main
        paths:
            - "*.tf"
            - "*.tfvars"
            - "modules/*/*"
    

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }} 
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }} 

jobs:
  opentofu-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.x 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Formatter
        run: tofu fmt

      - name: OpenTofu Format Check
        run: tofu fmt -check

      - name: OpenTofu Plan
        run: tofu plan
        
      - name: OpenTofu Apply
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve
